name: PNPM Workflow Build
on: 
  workflow_dispatch:
  
jobs:
  pnpm-start:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
    - name: Set job variables
      id: vars
      run: echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD)"

    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: PNPM install
      run: |
        pnpm install
        pnpm run build

    - name: Save artifacts
      uses: actions/cache@v2
      with:
        key: pnpm-artifacts-${{ github.sha }}
        path: |
          ./.next
          ./node_modules
          ./package.json

  build-mage:
    runs-on: ubuntu-20.04
    needs: pnpm-start
    steps:
    - uses: actions/checkout@v2

    - name: Set job variables
      id: vars
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        echo $GITHUB_REF
        echo $GITHUB_REF_NAME
        echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD)"
        echo "::set-output name=t::$(
          if [ $GITHUB_REF_NAME == "dev" ]; then echo "dev"; 
          elif [ $GITHUB_REF_NAME == "master" ]; then echo "prod";
          elif [ $GITHUB_REF_NAME == "github_actions" ]; then echo "prod";
          fi
        )"
    # - name: Take artifacts
    #   uses: actions/cache@v2
    #   with:
    #     key: pnpm-artifacts
    #     path: |
    #       ./.next
    #       ./node_modules
    #       ./package.json

    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GCP_GITHUB_ACTIONS_SA }}
        registry: gcr.io
        project_id: enterosoft
        image_name: frontend/askdom/${{ steps.vars.outputs.t }}
        image_tag: latest,${{ steps.vars.outputs.github_short_sha }}
        dockerfile: Dockerfile
        context: "."
